{{- if not .Values.runner.token.fromSecret -}}
{{- $token := .Values.runner.token.value | required ".Values.runner.token.value is required." -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "act_runner.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels: {{ include "act_runner.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
data:
  act-runner-token: {{ .Values.runner.token.value | b64enc }}
{{- end }}
