---
name: Release Helm Chart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  helm-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        with:
          skip_publish: ${{ github.event_name == 'pull_request' }}
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
